name: Build and Push Docker Image

on:
  push:
    branches:
      - main # 你可以修改这个为你的主要开发分支，比如 master 或其他名称。

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin myregistry.888122.xyz

      - name: Build and push Docker image
        run: |
          docker build -t myregistry.888122.xyz/pocketbase:latest .
          docker push myregistry.888122.xyz/pocketbase:latest
